version: '3.8'

services:
  fastapi:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/alembic:/app/alembic  # Mount the alembic directory to persist migrations
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  nextjs:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "9000:3000"
    depends_on:
      - fastapi

  db:
    image: postgres:15
    # latest supported version with at least one year of maturity as of 18/11/2023. https://www.postgresql.org/support/versioning/

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data: