name: USForestMonoRepo
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'backend/**'
      - 'frontend/**'

permissions:
  contents: read
  security-events: write
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  backendSonarCloudScan:
    name: Backend Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Setup Google Cloud Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > backend/google_cloud_keyfile_service_account.json
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run tests and generate coverage report
        run: |
          cd backend
          pytest --cov=./ --cov-report=xml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: backend/google_cloud_keyfile_service_account.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          secrets: inherit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: backend/

  frontendSonarCloudScan:
    name: Frontend Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Install dependencies
        run: |
          cd frontend/next-pages
          npm install
      - name: Build project
        run: |
          cd frontend/next-pages
          npm run build
      # If you have tests and want coverage:
      - name: Run tests and generate coverage report
        run: |
          cd frontend/next-pages
          npm run test -- --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          secrets: inherit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend/
